apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drone-runner-kubernetes.fullname" . }}
  labels:
    {{- include "drone-runner-kubernetes.labels" . | nindent 4 }}
data:
  DRONE_RPC_HOST: {{ .Values.drone.rpc.host | quote }}
  DRONE_RPC_PROTO: "http"
  DRONE_UI_USERNAME: {{ .Values.drone.ui.username | quote }}
  DRONE_NAMESPACE_DEFAULT: {{ .Values.drone.defaultNamespace | quote }}
  {{- if .Values.drone.env }}
  {{- .Values.drone.env | toYaml | nindent 2 }}
  {{- end }}
