apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drone.fullname" . }}-data
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
