apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
type: Opaque
data:
  rpcSecret: {{ .Values.drone.rpcSecret | b64enc | quote }}
  cookieSecret: {{ .Values.drone.cookieSecret | b64enc | quote }}
  {{- if .Values.drone.github.clientSecret }}
  githubClientSecret: {{ .Values.drone.github.clientSecret | b64enc | quote }}
  {{- end }}
