apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
type: Opaque
data:
  {{- .Values.drone.secretEnv | toYaml | nindent 2 }}
